theme: minima
title: Welcome!
author: Alex Mills
email: alex@millsmob.com.au
description: This is an awesome description for my new site.
twitter_username: alexmills3002
github_username:  alexmills802
show_excerpts: true
